dev:
   cid: gshgf65653%^%*(
   cpass: hshjs(*^*&fj
spotify:
  tokenUri: https://accounts.spotify.com/api/token
  someKey: spotify_test5_value
test:
  props:
    key1: value1
    key2: value2
    key3: value3
